---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: build-robot-role-binding
subjects:
- kind: ServiceAccount
  name: build-robot
  namespace: default
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: cluster-admin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: helloworld-image
spec:
  type: image
  params:
  - name: url
    value: example.com/rhdevelopers/helloworld
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: hello-git-source
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/kameshsampath/minikube-helpers